# kubectl apply -f josemaria-valenzuela-41-secret-fe.yml
apiVersion: v1
kind: Secret
metadata:
  name: josemaria-valenzuela-41-secret-fe
  namespace: josemaria-valenzuela-41-namespace-fe
type: Opaque
data:
  BACKEND_URL: aHR0cHM6Ly9zdXByZW1lLXNwYWNlLWZ1bmljdWxhci12Nmc5Zzc0dnI3anZocHhqNC0zMDAwMS5hcHAuZ2l0aHViLmRldg==
  NGINX_PORT: ODA=
# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode